---
# Default configuration file
provider: aws # Does not impact anything at this time but should in the future
#profile: prod-operations-user # AWS profile list maybe
region: us-east-1 # Can select any valid region or `random` to randomize regions

# List of playbooks to run
module:
  - name: Publicly Accessible S3 Bucket(Get)
    terraform_dir: terraform/exposed_services/aws_s3/public_get
  - name: Public SQS Queue
    terraform_dir: terraform/exposed_services/aws_sqs
  - name: Public Lambda Endpoint
    terraform_dir: terraform/exposed_services/aws_lambda/endpoint
  - name: Public ECR Gallery
    terraform_dir: terraform/exposed_services/aws_ecr/aws_ecr_public_gallery
  - name: S3 Bucket Takeover
    terraform_dir: terraform/misconfigurations/takeovers/aws_s3_takeover
    variables:
      resource_name: "securityrunners-images" # S3 bucket names must be globally unique
variables:
  resource_name: "securityrunners-images-prod" # Convincing resource name for all resources to be created as
  sensitive_content: "This is a message to provide to incident responders who have appropriately triaged the asset"
  tags:
    Name: "securityrunners-images-prod"
    Owner: "Operations"
    Project: "CloudCommotion"
