---
# Default configuration file
provider: aws # Does not impact anything at this time but should in the future
#profile: prod-operations-user # AWS profile list maybe
region: us-east-1 # Can select any valid region or `random` to randomize regions

# List of exercises to run
module:
  # This is for the VPC creation for exposed_assets to be created if you need a VPC 
  # - name: VPC Creation
  #   terraform_dir: terraform/environment/vpc
  - name: Publicly Accessible S3 Bucket(Get)
    terraform_dir: terraform/exposed_services/aws_s3/public_get
  - name: Public Lambda Endpoint
    terraform_dir: terraform/exposed_services/aws_lambda/endpoint
  - name: Public ECR Gallery
    terraform_dir: terraform/exposed_services/aws_ecr/aws_ecr_public_gallery
variables:
  resource_name: "securityrunners-static-website" # Convincing resource name for all resources to be created as
  sensitive_content: "This is a message to provide to incident responders who have appropriately triaged the asset"
  tags:
    Name: "securityrunners-static-website"
    Owner: "Operations"
    Project: "CloudCommotion"
