---
# Default configuration file
provider: aws # Does not impact anything at this time but should in the future
#profile: prod-operations-user # AWS profile list maybe
region: us-east-1 # Can select any valid region or `random` to randomize regions

# List of playbooks to run
module:
  - name: Publicly Accessible GCP Bucket object
    terraform_loc: local # Can be local or remote
    terraform_dir: terraform/exposed_services/google_datastore
    variables:
      region: us-central1
      project_name: SecurityRunners
variables:
  resource_name: "securityrunners-images-prod" # Convincing resource name for all resources to be created as
  sensitive_content: "This is a message to provide to incident responders who have appropriately triaged the asset"
  tags:
    Name: "securityrunners-images-prod"
    Owner: "Operations"
    Project: "CloudCommotion"
